apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bbr-configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bbr-configmap-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: bbr-plugins
roleRef:
  kind: ClusterRole
  name: bbr-configmap-reader
  apiGroup: rbac.authorization.k8s.io
